// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -package heartbeat -source manager.go -destination manager_mock.go
//

// Package heartbeat is a generated GoMock package.
package heartbeat

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	types "github.com/cadence-workflow/shard-manager/common/types"
)

// MockStateProvider is a mock of StateProvider interface.
type MockStateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStateProviderMockRecorder
	isgomock struct{}
}

// MockStateProviderMockRecorder is the mock recorder for MockStateProvider.
type MockStateProviderMockRecorder struct {
	mock *MockStateProvider
}

// NewMockStateProvider creates a new mock instance.
func NewMockStateProvider(ctrl *gomock.Controller) *MockStateProvider {
	mock := &MockStateProvider{ctrl: ctrl}
	mock.recorder = &MockStateProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateProvider) EXPECT() *MockStateProviderMockRecorder {
	return m.recorder
}

// GetMetadata mocks base method.
func (m *MockStateProvider) GetMetadata() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockStateProviderMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockStateProvider)(nil).GetMetadata))
}

// GetShardStatusReports mocks base method.
func (m *MockStateProvider) GetShardStatusReports() map[string]*types.ShardStatusReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShardStatusReports")
	ret0, _ := ret[0].(map[string]*types.ShardStatusReport)
	return ret0
}

// GetShardStatusReports indicates an expected call of GetShardStatusReports.
func (mr *MockStateProviderMockRecorder) GetShardStatusReports() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardStatusReports", reflect.TypeOf((*MockStateProvider)(nil).GetShardStatusReports))
}
