package grpc

// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/grpc.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	sharddistributorv1 "github.com/cadence-workflow/shard-manager/.gen/proto/sharddistributor/v1"
	"github.com/cadence-workflow/shard-manager/common/types"
	"github.com/cadence-workflow/shard-manager/common/types/mapper/proto"
	"github.com/cadence-workflow/shard-manager/service/sharddistributor/handler"
)

type GRPCHandler struct {
	h handler.Handler
}

func NewGRPCHandler(h handler.Handler) GRPCHandler {
	return GRPCHandler{h}
}

func (g GRPCHandler) DrainHosts(ctx context.Context, request *sharddistributorv1.DrainHostsRequest) (*sharddistributorv1.DrainHostsResponse, error) {
	err := g.h.DrainHosts(ctx, proto.ToShardDistributorDrainHostsRequest(request))
	return &sharddistributorv1.DrainHostsResponse{}, proto.FromError(err)
}

func (g GRPCHandler) DrainShards(ctx context.Context, request *sharddistributorv1.DrainShardsRequest) (*sharddistributorv1.DrainShardsResponse, error) {
	err := g.h.DrainShards(ctx, proto.ToShardDistributorDrainShardsRequest(request))
	return &sharddistributorv1.DrainShardsResponse{}, proto.FromError(err)
}

func (g GRPCHandler) ForceResetNamespace(ctx context.Context, request *sharddistributorv1.ForceResetNamespaceRequest) (*sharddistributorv1.ForceResetNamespaceResponse, error) {
	response, err := g.h.ForceResetNamespace(ctx, proto.ToShardDistributorForceResetNamespaceRequest(request))
	return proto.FromShardDistributorForceResetNamespaceResponse(response), proto.FromError(err)
}

func (g GRPCHandler) GetDrainedHosts(ctx context.Context, request *sharddistributorv1.GetDrainedHostsRequest) (*sharddistributorv1.GetDrainedHostsResponse, error) {
	response, err := g.h.GetDrainedHosts(ctx, proto.ToShardDistributorGetDrainedHostsRequest(request))
	return proto.FromShardDistributorGetDrainedHostsResponse(response), proto.FromError(err)
}

func (g GRPCHandler) GetDrainedShards(ctx context.Context, request *sharddistributorv1.GetDrainedShardsRequest) (*sharddistributorv1.GetDrainedShardsResponse, error) {
	response, err := g.h.GetDrainedShards(ctx, proto.ToShardDistributorGetDrainedShardsRequest(request))
	return proto.FromShardDistributorGetDrainedShardsResponse(response), proto.FromError(err)
}

func (g GRPCHandler) GetExecutorState(ctx context.Context, request *sharddistributorv1.GetExecutorStateRequest) (*sharddistributorv1.GetExecutorStateResponse, error) {
	response, err := g.h.GetExecutorState(ctx, proto.ToShardDistributorGetExecutorStateRequest(request))
	return proto.FromShardDistributorGetExecutorStateResponse(response), proto.FromError(err)
}

func (g GRPCHandler) GetNamespaceState(ctx context.Context, request *sharddistributorv1.GetNamespaceStateRequest) (*sharddistributorv1.GetNamespaceStateResponse, error) {
	response, err := g.h.GetNamespaceState(ctx, proto.ToShardDistributorGetNamespaceStateRequest(request))
	return proto.FromShardDistributorGetNamespaceStateResponse(response), proto.FromError(err)
}

func (g GRPCHandler) GetShardOwner(ctx context.Context, request *sharddistributorv1.GetShardOwnerRequest) (*sharddistributorv1.GetShardOwnerResponse, error) {
	response, err := g.h.GetShardOwner(ctx, proto.ToShardDistributorGetShardOwnerRequest(request))
	return proto.FromShardDistributorGetShardOwnerResponse(response), proto.FromError(err)
}

func (g GRPCHandler) InspectShard(ctx context.Context, request *sharddistributorv1.InspectShardRequest) (*sharddistributorv1.InspectShardResponse, error) {
	response, err := g.h.InspectShard(ctx, proto.ToShardDistributorInspectShardRequest(request))
	return proto.FromShardDistributorInspectShardResponse(response), proto.FromError(err)
}

func (g GRPCHandler) ListNamespaces(ctx context.Context, request *sharddistributorv1.ListNamespacesRequest) (*sharddistributorv1.ListNamespacesResponse, error) {
	response, err := g.h.ListNamespaces(ctx, proto.ToShardDistributorListNamespacesRequest(request))
	return proto.FromShardDistributorListNamespacesResponse(response), proto.FromError(err)
}

func (g GRPCHandler) UndrainHosts(ctx context.Context, request *sharddistributorv1.UndrainHostsRequest) (*sharddistributorv1.UndrainHostsResponse, error) {
	response, err := g.h.UndrainHosts(ctx, proto.ToShardDistributorUndrainHostsRequest(request))
	return proto.FromShardDistributorUndrainHostsResponse(response), proto.FromError(err)
}

func (g GRPCHandler) UndrainShards(ctx context.Context, request *sharddistributorv1.UndrainShardsRequest) (*sharddistributorv1.UndrainShardsResponse, error) {
	response, err := g.h.UndrainShards(ctx, proto.ToShardDistributorUndrainShardsRequest(request))
	return proto.FromShardDistributorUndrainShardsResponse(response), proto.FromError(err)
}

func (g GRPCHandler) WatchNamespaceState(request *sharddistributorv1.WatchNamespaceStateRequest, server sharddistributorv1.ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) error {
	err := g.h.WatchNamespaceState(proto.ToShardDistributorWatchNamespaceStateRequest(request), &watchnamespacestateServer{server: server})
	return err
}

type watchnamespacestateServer struct {
	server sharddistributorv1.ShardDistributorAPIServiceWatchNamespaceStateYARPCServer
}

func (s *watchnamespacestateServer) Context() context.Context {
	return s.server.Context()
}

func (s *watchnamespacestateServer) Send(response *types.WatchNamespaceStateResponse) error {
	return s.server.Send(proto.FromShardDistributorWatchNamespaceStateResponse(response))
}
