rpc:
  grpcPort: 7943
  bindOnLocalHost: true

metrics:
  statsd:
    hostPort: "127.0.0.1:8125"
    prefix: "cadence"

pprof:
  port: 7942

clusterGroupMetadata:
  currentClusterName: "cluster0"

dynamicconfig:
  client: filebased
  filebased:
    filepath: "config/dynamicconfig/development.yaml"
    pollInterval: "10s"

shardDistribution:
  election:
    leaderPeriod: 60s
    maxRandomDelay: 1s
    failedElectionCooldown: 1s
  namespaces:
    - name: shard-distributor-canary
      type: fixed
      shardNum: 32
    - name: shard-distributor-canary-ephemeral
      type: ephemeral
  leaderStore:
    storageParams:
      endpoints: ["localhost:2379"]
      dialTimeout: 1s
      prefix: "leader"
  store:
    storageParams:
      endpoints: ["localhost:2379"]
      dialTimeout: 1s
      prefix: "store"
  process:
    period: 1s
    heartbeatTTL: 2s
