// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/service.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCClient interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest, ...yarpc.CallOption) (*GetShardOwnerResponse, error)
	InspectShard(context.Context, *InspectShardRequest, ...yarpc.CallOption) (*InspectShardResponse, error)
	GetNamespaceState(context.Context, *GetNamespaceStateRequest, ...yarpc.CallOption) (*GetNamespaceStateResponse, error)
	GetExecutorState(context.Context, *GetExecutorStateRequest, ...yarpc.CallOption) (*GetExecutorStateResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest, ...yarpc.CallOption) (*ListNamespacesResponse, error)
	DrainShards(context.Context, *DrainShardsRequest, ...yarpc.CallOption) (*DrainShardsResponse, error)
	UndrainShards(context.Context, *UndrainShardsRequest, ...yarpc.CallOption) (*UndrainShardsResponse, error)
	GetDrainedShards(context.Context, *GetDrainedShardsRequest, ...yarpc.CallOption) (*GetDrainedShardsResponse, error)
	DrainHosts(context.Context, *DrainHostsRequest, ...yarpc.CallOption) (*DrainHostsResponse, error)
	UndrainHosts(context.Context, *UndrainHostsRequest, ...yarpc.CallOption) (*UndrainHostsResponse, error)
	GetDrainedHosts(context.Context, *GetDrainedHostsRequest, ...yarpc.CallOption) (*GetDrainedHostsResponse, error)
	ForceResetNamespace(context.Context, *ForceResetNamespaceRequest, ...yarpc.CallOption) (*ForceResetNamespaceResponse, error)
	WatchNamespaceState(context.Context, *WatchNamespaceStateRequest, ...yarpc.CallOption) (ShardDistributorAPIServiceWatchNamespaceStateYARPCClient, error)
}

// ShardDistributorAPIServiceWatchNamespaceStateYARPCClient receives WatchNamespaceStateResponses, returning io.EOF when the stream is complete.
type ShardDistributorAPIServiceWatchNamespaceStateYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*WatchNamespaceStateResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

func newShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return &_ShardDistributorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorAPIYARPCClient builds a new YARPC client for the ShardDistributorAPI service.
func NewShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return newShardDistributorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCServer interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest) (*GetShardOwnerResponse, error)
	InspectShard(context.Context, *InspectShardRequest) (*InspectShardResponse, error)
	GetNamespaceState(context.Context, *GetNamespaceStateRequest) (*GetNamespaceStateResponse, error)
	GetExecutorState(context.Context, *GetExecutorStateRequest) (*GetExecutorStateResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	DrainShards(context.Context, *DrainShardsRequest) (*DrainShardsResponse, error)
	UndrainShards(context.Context, *UndrainShardsRequest) (*UndrainShardsResponse, error)
	GetDrainedShards(context.Context, *GetDrainedShardsRequest) (*GetDrainedShardsResponse, error)
	DrainHosts(context.Context, *DrainHostsRequest) (*DrainHostsResponse, error)
	UndrainHosts(context.Context, *UndrainHostsRequest) (*UndrainHostsResponse, error)
	GetDrainedHosts(context.Context, *GetDrainedHostsRequest) (*GetDrainedHostsResponse, error)
	ForceResetNamespace(context.Context, *ForceResetNamespaceRequest) (*ForceResetNamespaceResponse, error)
	WatchNamespaceState(*WatchNamespaceStateRequest, ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) error
}

// ShardDistributorAPIServiceWatchNamespaceStateYARPCServer sends WatchNamespaceStateResponses.
type ShardDistributorAPIServiceWatchNamespaceStateYARPCServer interface {
	Context() context.Context
	Send(*WatchNamespaceStateResponse, ...yarpc.StreamOption) error
}

type buildShardDistributorAPIYARPCProceduresParams struct {
	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorAPIYARPCProcedures(params buildShardDistributorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "GetShardOwner",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetShardOwner,
							NewRequest:  newShardDistributorAPIServiceGetShardOwnerYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "InspectShard",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.InspectShard,
							NewRequest:  newShardDistributorAPIServiceInspectShardYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetNamespaceState",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetNamespaceState,
							NewRequest:  newShardDistributorAPIServiceGetNamespaceStateYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetExecutorState",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetExecutorState,
							NewRequest:  newShardDistributorAPIServiceGetExecutorStateYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "ListNamespaces",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.ListNamespaces,
							NewRequest:  newShardDistributorAPIServiceListNamespacesYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "DrainShards",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.DrainShards,
							NewRequest:  newShardDistributorAPIServiceDrainShardsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "UndrainShards",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.UndrainShards,
							NewRequest:  newShardDistributorAPIServiceUndrainShardsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetDrainedShards",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetDrainedShards,
							NewRequest:  newShardDistributorAPIServiceGetDrainedShardsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "DrainHosts",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.DrainHosts,
							NewRequest:  newShardDistributorAPIServiceDrainHostsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "UndrainHosts",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.UndrainHosts,
							NewRequest:  newShardDistributorAPIServiceUndrainHostsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "GetDrainedHosts",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetDrainedHosts,
							NewRequest:  newShardDistributorAPIServiceGetDrainedHostsYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
				{
					MethodName: "ForceResetNamespace",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.ForceResetNamespace,
							NewRequest:  newShardDistributorAPIServiceForceResetNamespaceYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{

				{
					MethodName: "WatchNamespaceState",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.WatchNamespaceState,
						},
					),
				},
			},
		},
	)
}

// BuildShardDistributorAPIYARPCProcedures prepares an implementation of the ShardDistributorAPI service for YARPC registration.
func BuildShardDistributorAPIYARPCProcedures(server ShardDistributorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorAPIYARPCClientParams defines the input
// for NewFxShardDistributorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorAPIYARPCClient in an
// Fx application.
type FxShardDistributorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorAPIYARPCClientResult defines the output
// of NewFxShardDistributorAPIYARPCClient. It provides a
// ShardDistributorAPIYARPCClient to an Fx application.
type FxShardDistributorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorAPIYARPCClient provides a ShardDistributorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorAPIYARPCClientParams) FxShardDistributorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorAPIYARPCClientResult{
			Client: newShardDistributorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorAPIYARPCProcedures. It provides
// ShardDistributorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorAPIYARPCProcedures provides ShardDistributorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorAPIYARPCProceduresParams) FxShardDistributorAPIYARPCProceduresResult {
		return FxShardDistributorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorAPIReflectionMeta,
		}
	}
}

// ShardDistributorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
	FileDescriptors: yarpcFileDescriptorClosure0055bfd59dff1f95,
}

type _ShardDistributorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorAPIYARPCCaller) GetShardOwner(ctx context.Context, request *GetShardOwnerRequest, options ...yarpc.CallOption) (*GetShardOwnerResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetShardOwner", request, newShardDistributorAPIServiceGetShardOwnerYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetShardOwnerResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) InspectShard(ctx context.Context, request *InspectShardRequest, options ...yarpc.CallOption) (*InspectShardResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "InspectShard", request, newShardDistributorAPIServiceInspectShardYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*InspectShardResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceInspectShardYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) GetNamespaceState(ctx context.Context, request *GetNamespaceStateRequest, options ...yarpc.CallOption) (*GetNamespaceStateResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetNamespaceState", request, newShardDistributorAPIServiceGetNamespaceStateYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetNamespaceStateResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetNamespaceStateYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) GetExecutorState(ctx context.Context, request *GetExecutorStateRequest, options ...yarpc.CallOption) (*GetExecutorStateResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetExecutorState", request, newShardDistributorAPIServiceGetExecutorStateYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetExecutorStateResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetExecutorStateYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) ListNamespaces(ctx context.Context, request *ListNamespacesRequest, options ...yarpc.CallOption) (*ListNamespacesResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "ListNamespaces", request, newShardDistributorAPIServiceListNamespacesYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*ListNamespacesResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceListNamespacesYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) DrainShards(ctx context.Context, request *DrainShardsRequest, options ...yarpc.CallOption) (*DrainShardsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "DrainShards", request, newShardDistributorAPIServiceDrainShardsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*DrainShardsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceDrainShardsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) UndrainShards(ctx context.Context, request *UndrainShardsRequest, options ...yarpc.CallOption) (*UndrainShardsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "UndrainShards", request, newShardDistributorAPIServiceUndrainShardsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*UndrainShardsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceUndrainShardsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) GetDrainedShards(ctx context.Context, request *GetDrainedShardsRequest, options ...yarpc.CallOption) (*GetDrainedShardsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetDrainedShards", request, newShardDistributorAPIServiceGetDrainedShardsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetDrainedShardsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetDrainedShardsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) DrainHosts(ctx context.Context, request *DrainHostsRequest, options ...yarpc.CallOption) (*DrainHostsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "DrainHosts", request, newShardDistributorAPIServiceDrainHostsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*DrainHostsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceDrainHostsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) UndrainHosts(ctx context.Context, request *UndrainHostsRequest, options ...yarpc.CallOption) (*UndrainHostsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "UndrainHosts", request, newShardDistributorAPIServiceUndrainHostsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*UndrainHostsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceUndrainHostsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) GetDrainedHosts(ctx context.Context, request *GetDrainedHostsRequest, options ...yarpc.CallOption) (*GetDrainedHostsResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetDrainedHosts", request, newShardDistributorAPIServiceGetDrainedHostsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetDrainedHostsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetDrainedHostsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) ForceResetNamespace(ctx context.Context, request *ForceResetNamespaceRequest, options ...yarpc.CallOption) (*ForceResetNamespaceResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "ForceResetNamespace", request, newShardDistributorAPIServiceForceResetNamespaceYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*ForceResetNamespaceResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceForceResetNamespaceYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIYARPCCaller) WatchNamespaceState(ctx context.Context, request *WatchNamespaceStateRequest, options ...yarpc.CallOption) (ShardDistributorAPIServiceWatchNamespaceStateYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "WatchNamespaceState", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient{stream: stream}, nil
}

type _ShardDistributorAPIYARPCHandler struct {
	server ShardDistributorAPIYARPCServer
}

func (h *_ShardDistributorAPIYARPCHandler) GetShardOwner(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetShardOwnerRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetShardOwnerRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetShardOwner(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) InspectShard(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *InspectShardRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*InspectShardRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceInspectShardYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.InspectShard(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) GetNamespaceState(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetNamespaceStateRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetNamespaceStateRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetNamespaceStateYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetNamespaceState(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) GetExecutorState(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetExecutorStateRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetExecutorStateRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetExecutorStateYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetExecutorState(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) ListNamespaces(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *ListNamespacesRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*ListNamespacesRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceListNamespacesYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.ListNamespaces(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) DrainShards(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *DrainShardsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*DrainShardsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceDrainShardsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.DrainShards(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) UndrainShards(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *UndrainShardsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*UndrainShardsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceUndrainShardsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.UndrainShards(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) GetDrainedShards(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetDrainedShardsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetDrainedShardsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetDrainedShardsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetDrainedShards(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) DrainHosts(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *DrainHostsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*DrainHostsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceDrainHostsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.DrainHosts(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) UndrainHosts(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *UndrainHostsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*UndrainHostsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceUndrainHostsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.UndrainHosts(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) GetDrainedHosts(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetDrainedHostsRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetDrainedHostsRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetDrainedHostsYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetDrainedHosts(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) ForceResetNamespace(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *ForceResetNamespaceRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*ForceResetNamespaceRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceForceResetNamespaceYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.ForceResetNamespace(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func (h *_ShardDistributorAPIYARPCHandler) WatchNamespaceState(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newShardDistributorAPIServiceWatchNamespaceStateYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*WatchNamespaceStateRequest)
	if !ok {
		return protobuf.CastError(emptyShardDistributorAPIServiceWatchNamespaceStateYARPCRequest, requestMessage)
	}
	return h.server.WatchNamespaceState(request, &_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer{serverStream: serverStream})
}

type _ShardDistributorAPIServiceWatchNamespaceStateYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) Recv(options ...yarpc.StreamOption) (*WatchNamespaceStateResponse, error) {
	responseMessage, err := c.stream.Receive(newShardDistributorAPIServiceWatchNamespaceStateYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*WatchNamespaceStateResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceWatchNamespaceStateYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_ShardDistributorAPIServiceWatchNamespaceStateYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _ShardDistributorAPIServiceWatchNamespaceStateYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_ShardDistributorAPIServiceWatchNamespaceStateYARPCServer) Send(response *WatchNamespaceStateResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

func newShardDistributorAPIServiceGetShardOwnerYARPCRequest() proto.Message {
	return &GetShardOwnerRequest{}
}

func newShardDistributorAPIServiceGetShardOwnerYARPCResponse() proto.Message {
	return &GetShardOwnerResponse{}
}

func newShardDistributorAPIServiceInspectShardYARPCRequest() proto.Message {
	return &InspectShardRequest{}
}

func newShardDistributorAPIServiceInspectShardYARPCResponse() proto.Message {
	return &InspectShardResponse{}
}

func newShardDistributorAPIServiceGetNamespaceStateYARPCRequest() proto.Message {
	return &GetNamespaceStateRequest{}
}

func newShardDistributorAPIServiceGetNamespaceStateYARPCResponse() proto.Message {
	return &GetNamespaceStateResponse{}
}

func newShardDistributorAPIServiceGetExecutorStateYARPCRequest() proto.Message {
	return &GetExecutorStateRequest{}
}

func newShardDistributorAPIServiceGetExecutorStateYARPCResponse() proto.Message {
	return &GetExecutorStateResponse{}
}

func newShardDistributorAPIServiceWatchNamespaceStateYARPCRequest() proto.Message {
	return &WatchNamespaceStateRequest{}
}

func newShardDistributorAPIServiceWatchNamespaceStateYARPCResponse() proto.Message {
	return &WatchNamespaceStateResponse{}
}

func newShardDistributorAPIServiceListNamespacesYARPCRequest() proto.Message {
	return &ListNamespacesRequest{}
}

func newShardDistributorAPIServiceListNamespacesYARPCResponse() proto.Message {
	return &ListNamespacesResponse{}
}

func newShardDistributorAPIServiceDrainShardsYARPCRequest() proto.Message {
	return &DrainShardsRequest{}
}

func newShardDistributorAPIServiceDrainShardsYARPCResponse() proto.Message {
	return &DrainShardsResponse{}
}

func newShardDistributorAPIServiceUndrainShardsYARPCRequest() proto.Message {
	return &UndrainShardsRequest{}
}

func newShardDistributorAPIServiceUndrainShardsYARPCResponse() proto.Message {
	return &UndrainShardsResponse{}
}

func newShardDistributorAPIServiceGetDrainedShardsYARPCRequest() proto.Message {
	return &GetDrainedShardsRequest{}
}

func newShardDistributorAPIServiceGetDrainedShardsYARPCResponse() proto.Message {
	return &GetDrainedShardsResponse{}
}

func newShardDistributorAPIServiceDrainHostsYARPCRequest() proto.Message {
	return &DrainHostsRequest{}
}

func newShardDistributorAPIServiceDrainHostsYARPCResponse() proto.Message {
	return &DrainHostsResponse{}
}

func newShardDistributorAPIServiceUndrainHostsYARPCRequest() proto.Message {
	return &UndrainHostsRequest{}
}

func newShardDistributorAPIServiceUndrainHostsYARPCResponse() proto.Message {
	return &UndrainHostsResponse{}
}

func newShardDistributorAPIServiceGetDrainedHostsYARPCRequest() proto.Message {
	return &GetDrainedHostsRequest{}
}

func newShardDistributorAPIServiceGetDrainedHostsYARPCResponse() proto.Message {
	return &GetDrainedHostsResponse{}
}

func newShardDistributorAPIServiceForceResetNamespaceYARPCRequest() proto.Message {
	return &ForceResetNamespaceRequest{}
}

func newShardDistributorAPIServiceForceResetNamespaceYARPCResponse() proto.Message {
	return &ForceResetNamespaceResponse{}
}

var (
	emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest        = &GetShardOwnerRequest{}
	emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse       = &GetShardOwnerResponse{}
	emptyShardDistributorAPIServiceInspectShardYARPCRequest         = &InspectShardRequest{}
	emptyShardDistributorAPIServiceInspectShardYARPCResponse        = &InspectShardResponse{}
	emptyShardDistributorAPIServiceGetNamespaceStateYARPCRequest    = &GetNamespaceStateRequest{}
	emptyShardDistributorAPIServiceGetNamespaceStateYARPCResponse   = &GetNamespaceStateResponse{}
	emptyShardDistributorAPIServiceGetExecutorStateYARPCRequest     = &GetExecutorStateRequest{}
	emptyShardDistributorAPIServiceGetExecutorStateYARPCResponse    = &GetExecutorStateResponse{}
	emptyShardDistributorAPIServiceWatchNamespaceStateYARPCRequest  = &WatchNamespaceStateRequest{}
	emptyShardDistributorAPIServiceWatchNamespaceStateYARPCResponse = &WatchNamespaceStateResponse{}
	emptyShardDistributorAPIServiceListNamespacesYARPCRequest       = &ListNamespacesRequest{}
	emptyShardDistributorAPIServiceListNamespacesYARPCResponse      = &ListNamespacesResponse{}
	emptyShardDistributorAPIServiceDrainShardsYARPCRequest          = &DrainShardsRequest{}
	emptyShardDistributorAPIServiceDrainShardsYARPCResponse         = &DrainShardsResponse{}
	emptyShardDistributorAPIServiceUndrainShardsYARPCRequest        = &UndrainShardsRequest{}
	emptyShardDistributorAPIServiceUndrainShardsYARPCResponse       = &UndrainShardsResponse{}
	emptyShardDistributorAPIServiceGetDrainedShardsYARPCRequest     = &GetDrainedShardsRequest{}
	emptyShardDistributorAPIServiceGetDrainedShardsYARPCResponse    = &GetDrainedShardsResponse{}
	emptyShardDistributorAPIServiceDrainHostsYARPCRequest           = &DrainHostsRequest{}
	emptyShardDistributorAPIServiceDrainHostsYARPCResponse          = &DrainHostsResponse{}
	emptyShardDistributorAPIServiceUndrainHostsYARPCRequest         = &UndrainHostsRequest{}
	emptyShardDistributorAPIServiceUndrainHostsYARPCResponse        = &UndrainHostsResponse{}
	emptyShardDistributorAPIServiceGetDrainedHostsYARPCRequest      = &GetDrainedHostsRequest{}
	emptyShardDistributorAPIServiceGetDrainedHostsYARPCResponse     = &GetDrainedHostsResponse{}
	emptyShardDistributorAPIServiceForceResetNamespaceYARPCRequest  = &ForceResetNamespaceRequest{}
	emptyShardDistributorAPIServiceForceResetNamespaceYARPCResponse = &ForceResetNamespaceResponse{}
)

var yarpcFileDescriptorClosure0055bfd59dff1f95 = [][]byte{
	// uber/cadence/sharddistributor/v1/service.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5b, 0x6f, 0x1b, 0xc5,
		0x17, 0xd7, 0xda, 0x4d, 0x14, 0x9f, 0x34, 0xb7, 0xb1, 0x93, 0xfa, 0xbf, 0xe9, 0x5f, 0x0d, 0x2b,
		0x24, 0xf2, 0x40, 0xd6, 0x49, 0x9a, 0xa6, 0xb9, 0x50, 0x41, 0xda, 0x5c, 0x45, 0x9b, 0x36, 0x9b,
		0x42, 0x2b, 0x50, 0x65, 0xc6, 0xde, 0x89, 0xb3, 0x24, 0xde, 0x35, 0x3b, 0xb3, 0x0e, 0x46, 0x20,
		0x21, 0x21, 0x81, 0x90, 0x10, 0x12, 0x88, 0x17, 0xc4, 0xf7, 0xe1, 0x9d, 0x8f, 0x81, 0x78, 0xe1,
		0x23, 0xa0, 0x9d, 0x9d, 0xbd, 0x66, 0x63, 0xaf, 0x9d, 0xc2, 0x9b, 0x3d, 0x33, 0xe7, 0x9c, 0xdf,
		0x39, 0xf3, 0x3b, 0x97, 0x59, 0x50, 0x9d, 0x1a, 0xb1, 0x2b, 0x75, 0xac, 0x13, 0xb3, 0x4e, 0x2a,
		0xf4, 0x14, 0xdb, 0xba, 0x6e, 0x50, 0x66, 0x1b, 0x35, 0x87, 0x59, 0x76, 0xa5, 0xbd, 0x54, 0xa1,
		0xc4, 0x6e, 0x1b, 0x75, 0xa2, 0xb6, 0x6c, 0x8b, 0x59, 0x68, 0xce, 0x3d, 0xaf, 0x8a, 0xf3, 0x6a,
		0xf2, 0xbc, 0xda, 0x5e, 0x92, 0xef, 0x34, 0x2c, 0xab, 0x71, 0x4e, 0x2a, 0xfc, 0x7c, 0xcd, 0x39,
		0xa9, 0x30, 0xa3, 0x49, 0x28, 0xc3, 0xcd, 0x96, 0xa7, 0x42, 0xae, 0xf4, 0x34, 0x49, 0x3e, 0x27,
		0x75, 0xae, 0x8e, 0x0b, 0x28, 0x47, 0x50, 0xda, 0x23, 0xec, 0xd8, 0x3d, 0xf8, 0xf4, 0xc2, 0x24,
		0xb6, 0x46, 0x3e, 0x73, 0x08, 0x65, 0x68, 0x16, 0x0a, 0x5c, 0xba, 0x7a, 0x46, 0x3a, 0x65, 0x69,
		0x4e, 0x9a, 0x2f, 0x68, 0x23, 0x7c, 0xe1, 0x7d, 0xd2, 0x41, 0xb7, 0xa1, 0x60, 0xe2, 0x26, 0xa1,
		0x2d, 0x5c, 0x27, 0xe5, 0x1c, 0xdf, 0x0c, 0x17, 0x94, 0xbf, 0x24, 0x98, 0x4e, 0xe8, 0xa4, 0x2d,
		0xcb, 0xa4, 0x04, 0x95, 0x60, 0xc8, 0x72, 0x17, 0x84, 0x42, 0xef, 0x4f, 0x77, 0x6d, 0x08, 0xc3,
		0x48, 0x93, 0x30, 0xac, 0x63, 0x86, 0xcb, 0xf9, 0xb9, 0xfc, 0xfc, 0xe8, 0xf2, 0x8e, 0xda, 0x2b,
		0x4e, 0x6a, 0xaa, 0x79, 0xf5, 0x89, 0xd0, 0xb3, 0x63, 0x32, 0xbb, 0xa3, 0x05, 0x6a, 0xe5, 0x4d,
		0x18, 0x8b, 0x6d, 0xa1, 0x49, 0xc8, 0x87, 0x6e, 0xbb, 0x3f, 0x5d, 0xe4, 0x6d, 0x7c, 0xee, 0xf8,
		0xf8, 0xbc, 0x3f, 0x1b, 0xb9, 0x35, 0x49, 0x79, 0x06, 0xc5, 0x03, 0x93, 0xb6, 0x48, 0xdd, 0xb3,
		0xf8, 0x1a, 0xe2, 0xf7, 0xa7, 0x04, 0xa5, 0xb8, 0xca, 0x6b, 0x84, 0xef, 0x93, 0x4b, 0xe1, 0xdb,
		0xee, 0x1d, 0xbe, 0x34, 0xeb, 0xff, 0x4e, 0xf4, 0x56, 0x61, 0xe6, 0xd0, 0xc7, 0x7a, 0x68, 0xb1,
		0x5d, 0xcb, 0x31, 0xf5, 0x1d, 0xdb, 0xb6, 0x12, 0x6e, 0x49, 0xc9, 0x18, 0x3d, 0x05, 0xc4, 0xd1,
		0xf5, 0x21, 0x13, 0xbf, 0x92, 0x5c, 0xfc, 0x4a, 0x94, 0x43, 0x98, 0xe2, 0x0a, 0xb7, 0x6d, 0x6c,
		0x98, 0xe4, 0xfa, 0xfa, 0xd6, 0xa0, 0xbc, 0x47, 0x58, 0xe0, 0xdb, 0x31, 0xc3, 0x8c, 0xf8, 0xdc,
		0xe8, 0xee, 0xda, 0x4f, 0x12, 0xfc, 0x2f, 0x45, 0x54, 0x70, 0xa0, 0x3b, 0xa4, 0x0f, 0xa1, 0xe0,
		0xe7, 0x37, 0x2d, 0xe7, 0xf8, 0x75, 0xaf, 0xf5, 0xbe, 0xee, 0xc0, 0xd4, 0x8e, 0x90, 0xf5, 0x4c,
		0x86, 0xaa, 0x94, 0xdf, 0xf3, 0x91, 0x7b, 0x8a, 0x9d, 0x42, 0x77, 0x60, 0xd4, 0x3f, 0x57, 0x35,
		0x74, 0x01, 0x09, 0xfc, 0xa5, 0x03, 0x1d, 0xed, 0xc3, 0x30, 0x65, 0x98, 0x39, 0x94, 0xc7, 0x68,
		0x7c, 0x79, 0xb1, 0x37, 0xa0, 0xa8, 0x05, 0x87, 0x6a, 0x42, 0x1e, 0x6d, 0xc1, 0xf8, 0x39, 0xa6,
		0xac, 0x7a, 0x4a, 0xb0, 0xcd, 0x6a, 0x04, 0xb3, 0x72, 0x7e, 0x4e, 0x9a, 0x1f, 0x5d, 0x96, 0x55,
		0xaf, 0x2c, 0xaa, 0x7e, 0x59, 0x54, 0x9f, 0xfb, 0x65, 0x51, 0x1b, 0x73, 0x25, 0xf6, 0x7d, 0x01,
		0x54, 0x8b, 0xa4, 0xc3, 0x0d, 0x1e, 0x9f, 0xdd, 0x41, 0xe3, 0x73, 0x55, 0x42, 0xa0, 0x57, 0x30,
		0x81, 0x29, 0x35, 0x1a, 0x26, 0xd1, 0xab, 0x5c, 0x1d, 0x2d, 0x0f, 0x71, 0x53, 0x2b, 0xbd, 0x4d,
		0x6d, 0x09, 0x41, 0xce, 0x45, 0xef, 0x1a, 0xc6, 0x71, 0x74, 0x8d, 0x5e, 0x2f, 0xdf, 0xfe, 0x90,
		0x00, 0x5d, 0xb6, 0xd1, 0xbd, 0x5a, 0x55, 0x61, 0xca, 0x83, 0xd0, 0x24, 0x26, 0xab, 0xc6, 0xee,
		0x72, 0x39, 0xab, 0x47, 0xae, 0xa8, 0xb8, 0xcd, 0x49, 0x9c, 0x58, 0x41, 0x0f, 0x60, 0x36, 0x0c,
		0x98, 0x8b, 0xa7, 0xda, 0xb4, 0xf4, 0xaa, 0x4d, 0xda, 0x06, 0x35, 0x2c, 0x93, 0x5f, 0x72, 0x5e,
		0x2b, 0x07, 0x61, 0x70, 0x4f, 0x3c, 0xb1, 0x74, 0x4d, 0xec, 0x2b, 0x2f, 0xe1, 0xd6, 0x1e, 0x61,
		0x71, 0xee, 0x66, 0xc9, 0xb4, 0x24, 0x75, 0x73, 0x49, 0xea, 0x2a, 0x3f, 0x4a, 0x3c, 0x8b, 0x13,
		0xaa, 0x33, 0x65, 0xe2, 0x73, 0x18, 0xf1, 0x15, 0x71, 0xc5, 0xd7, 0x49, 0xc4, 0x40, 0x93, 0xb2,
		0x01, 0xf2, 0x0b, 0xcc, 0xea, 0xa7, 0x83, 0xd4, 0x95, 0x5f, 0x25, 0x98, 0x4d, 0x15, 0x16, 0xfe,
		0x3c, 0x8e, 0xd6, 0x0e, 0x89, 0x13, 0x56, 0xcd, 0x9e, 0xaa, 0x07, 0xe6, 0x89, 0x15, 0xa9, 0x18,
		0xe8, 0x6d, 0x40, 0xba, 0x57, 0x4a, 0xab, 0x01, 0xb3, 0xbc, 0x92, 0x54, 0xd0, 0x26, 0xc5, 0xce,
		0xb1, 0x60, 0x18, 0x55, 0xbe, 0xcb, 0xc1, 0xcd, 0xa8, 0xa6, 0xde, 0x55, 0xe5, 0x65, 0x24, 0x91,
		0xbd, 0x42, 0xf7, 0x4e, 0x7f, 0x60, 0xaf, 0x4c, 0xdf, 0x77, 0x61, 0x58, 0x64, 0xad, 0xd7, 0x2f,
		0xdf, 0xea, 0xad, 0xd7, 0x6b, 0x94, 0x42, 0xec, 0x7a, 0x09, 0xfa, 0x26, 0x0c, 0x71, 0x6d, 0x5d,
		0x53, 0x52, 0xb9, 0x05, 0xd3, 0x8f, 0x0d, 0x1a, 0xf6, 0x08, 0x2a, 0x28, 0xa0, 0x9c, 0xc1, 0x4c,
		0x72, 0x43, 0x5c, 0xef, 0x11, 0x40, 0xc0, 0x05, 0xff, 0x7e, 0x97, 0xfa, 0xa0, 0xe4, 0x23, 0xcb,
		0x3c, 0x31, 0x1a, 0x5a, 0x44, 0x89, 0xf2, 0x29, 0x4c, 0x24, 0xb6, 0x11, 0x82, 0x1b, 0xee, 0x01,
		0x01, 0x98, 0xff, 0x76, 0xd7, 0x58, 0xa7, 0xe5, 0xfb, 0xca, 0x7f, 0xbb, 0x6b, 0x4d, 0x4b, 0x27,
		0x3c, 0xb7, 0x0b, 0x1a, 0xff, 0x1d, 0x7a, 0x6c, 0x3a, 0xcd, 0xf2, 0x0d, 0x9e, 0xf4, 0x9e, 0xc7,
		0x87, 0x4e, 0x53, 0x39, 0x02, 0xc4, 0x5b, 0xb3, 0x57, 0x04, 0xb3, 0xe5, 0xf7, 0xff, 0x01, 0x2e,
		0x71, 0xaf, 0x40, 0x03, 0xd2, 0x4d, 0x43, 0x31, 0xa6, 0xd2, 0x0b, 0x94, 0x72, 0x0c, 0xa5, 0x0f,
		0x4c, 0xfd, 0x35, 0xdb, 0x3a, 0x80, 0xe9, 0x84, 0x52, 0x71, 0x2d, 0x8b, 0x50, 0x72, 0xcc, 0x94,
		0x4c, 0x91, 0xb8, 0x06, 0x14, 0xec, 0x85, 0xb9, 0x72, 0x9f, 0x97, 0xbb, 0xed, 0xc8, 0x72, 0x36,
		0x88, 0xca, 0x0b, 0x5e, 0xcc, 0x12, 0x82, 0x99, 0x8a, 0x59, 0x0f, 0xe7, 0x7e, 0x93, 0x60, 0x54,
		0xa8, 0xdd, 0xb7, 0x28, 0x43, 0x32, 0x8c, 0x9c, 0x5a, 0x94, 0x45, 0x88, 0x10, 0xfc, 0x47, 0xeb,
		0x00, 0xbe, 0xb7, 0x98, 0x89, 0xca, 0xd8, 0xad, 0x7f, 0x17, 0xc4, 0xe9, 0x2d, 0xe6, 0xa2, 0xf0,
		0x45, 0x6b, 0x1d, 0xc1, 0x1c, 0x7f, 0xfb, 0x61, 0x07, 0xcd, 0xc0, 0xb0, 0x4d, 0x30, 0xb5, 0x4c,
		0xce, 0x9d, 0x82, 0x26, 0xfe, 0x29, 0x6d, 0x98, 0xe2, 0xe0, 0x5c, 0x68, 0x19, 0x2f, 0xf3, 0x11,
		0x0c, 0xb9, 0x80, 0xfd, 0x11, 0x6a, 0xa1, 0x77, 0x9a, 0x44, 0xdc, 0xd7, 0x3c, 0x59, 0xa5, 0x24,
		0x18, 0x2b, 0xec, 0x0a, 0x76, 0x1d, 0x41, 0x51, 0x10, 0xa1, 0x0f, 0x3c, 0xb7, 0xa1, 0xe0, 0x07,
		0x30, 0x08, 0x7f, 0xb0, 0xa0, 0xec, 0x05, 0x84, 0x8d, 0x99, 0x42, 0x15, 0x28, 0x86, 0xd4, 0x0a,
		0xe5, 0x93, 0xcc, 0xda, 0x0f, 0x14, 0xad, 0xc2, 0x4c, 0x48, 0x90, 0xec, 0xf0, 0x94, 0x2f, 0xa3,
		0x8c, 0x8c, 0x63, 0xf8, 0x0f, 0xe2, 0xbc, 0x01, 0xf2, 0xae, 0x65, 0xd7, 0xdd, 0x46, 0x16, 0x99,
		0x9a, 0xb3, 0x21, 0x7f, 0x0f, 0x66, 0x53, 0x65, 0x05, 0xfa, 0x37, 0xe0, 0xa6, 0x4e, 0xce, 0x09,
		0x23, 0x41, 0x52, 0xba, 0x45, 0x69, 0x54, 0xac, 0xb9, 0xdc, 0x5f, 0xfe, 0x7b, 0x0c, 0x8a, 0xde,
		0xc3, 0x21, 0x04, 0xba, 0xf5, 0xec, 0x00, 0x7d, 0x2d, 0xc1, 0x58, 0xec, 0x15, 0x8a, 0x56, 0xfb,
		0x7e, 0xb6, 0x72, 0x0f, 0xe4, 0xfb, 0x03, 0x3e, 0x77, 0xd1, 0x57, 0x70, 0x33, 0xfa, 0x90, 0x43,
		0xf7, 0xfa, 0x7d, 0xf8, 0x79, 0xf6, 0x57, 0x07, 0x7b, 0x2f, 0xa2, 0x1f, 0x24, 0x98, 0xba, 0xf4,
		0x8e, 0x41, 0x1b, 0x99, 0xbc, 0x49, 0x9d, 0x6f, 0xe4, 0xcd, 0x81, 0x64, 0x05, 0x9c, 0xef, 0x25,
		0x98, 0x4c, 0xce, 0x72, 0x68, 0x3d, 0x93, 0xc6, 0xb4, 0xd1, 0x52, 0xde, 0x18, 0x44, 0x54, 0x60,
		0xf9, 0x45, 0x82, 0x62, 0xca, 0x28, 0x86, 0x32, 0x8c, 0x30, 0x57, 0x8f, 0x7f, 0xf2, 0x83, 0x01,
		0xa5, 0x3d, 0x50, 0x8b, 0x12, 0xfa, 0x46, 0x82, 0xf1, 0xf8, 0xf4, 0x80, 0x32, 0x90, 0x2f, 0x75,
		0x10, 0x91, 0xd7, 0xfa, 0x17, 0x14, 0xc1, 0xf9, 0x42, 0x34, 0x13, 0xaf, 0x43, 0xa1, 0x95, 0x8c,
		0x45, 0x21, 0xd6, 0x09, 0xe5, 0x7b, 0x7d, 0x4a, 0x09, 0xdb, 0x6e, 0xd6, 0xc6, 0xfa, 0x74, 0x96,
		0xac, 0x4d, 0x9b, 0x16, 0xb2, 0x64, 0x6d, 0xfa, 0x40, 0x20, 0x78, 0x1a, 0x6b, 0xd3, 0x19, 0x79,
		0x9a, 0x36, 0x13, 0x64, 0xe4, 0x69, 0xfa, 0x54, 0x70, 0x01, 0x10, 0xb6, 0x30, 0x74, 0x37, 0x63,
		0x4c, 0xa3, 0x9d, 0x43, 0x5e, 0xe9, 0x4f, 0x28, 0x2c, 0x5d, 0xd1, 0x96, 0x96, 0xa5, 0x74, 0xa5,
		0x74, 0x55, 0x79, 0xb5, 0x5f, 0x31, 0x61, 0xfe, 0x5b, 0x09, 0x26, 0x12, 0x1d, 0x0d, 0xad, 0xf5,
		0x13, 0xc7, 0x18, 0x8a, 0xf5, 0x01, 0x24, 0x05, 0x90, 0x9f, 0x25, 0x28, 0xa6, 0x34, 0xa8, 0x2c,
		0x85, 0xe2, 0xea, 0x9e, 0x98, 0xa5, 0x50, 0x74, 0xe9, 0x8a, 0x0f, 0x5f, 0x7d, 0xf4, 0x71, 0xc3,
		0x60, 0xa7, 0x4e, 0x4d, 0xad, 0x5b, 0x4d, 0xff, 0x5b, 0xf3, 0xc2, 0x85, 0x65, 0x9f, 0x9d, 0x9c,
		0x5b, 0x17, 0xde, 0x47, 0xe7, 0x85, 0x26, 0x36, 0x71, 0x83, 0xd8, 0x15, 0xb5, 0x41, 0x4c, 0xef,
		0x73, 0x75, 0xda, 0xd7, 0xe8, 0xcd, 0xe4, 0x5a, 0x7b, 0xa9, 0x36, 0xcc, 0x4f, 0xdf, 0xfd, 0x27,
		0x00, 0x00, 0xff, 0xff, 0xc3, 0xe7, 0x7c, 0x49, 0x3e, 0x17, 0x00, 0x00,
	},
	// google/protobuf/timestamp.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xcf, 0xcf, 0x4f,
		0xcf, 0x49, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0xc9, 0xcc, 0x4d,
		0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xd0, 0x03, 0x0b, 0x09, 0xf1, 0x43, 0x14, 0xe8, 0xc1, 0x14, 0x28,
		0x59, 0x73, 0x71, 0x86, 0xc0, 0xd4, 0x08, 0x49, 0x70, 0xb1, 0x17, 0xa7, 0x26, 0xe7, 0xe7, 0xa5,
		0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x42, 0x22, 0x5c, 0xac, 0x79, 0x89,
		0x79, 0xf9, 0xc5, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x53, 0x2b, 0x23, 0x97,
		0x70, 0x72, 0x7e, 0xae, 0x1e, 0x9a, 0xa1, 0x4e, 0x7c, 0x70, 0x23, 0x03, 0x40, 0x42, 0x01, 0x8c,
		0x51, 0x46, 0x50, 0x25, 0xe9, 0xf9, 0x39, 0x89, 0x79, 0xe9, 0x7a, 0xf9, 0x45, 0xe9, 0x48, 0x6e,
		0xac, 0x2c, 0x48, 0x2d, 0xd6, 0xcf, 0xce, 0xcb, 0x2f, 0xcf, 0x43, 0xb8, 0xb7, 0x20, 0xe9, 0x07,
		0x23, 0xe3, 0x22, 0x26, 0x66, 0xf7, 0x00, 0xa7, 0x55, 0x4c, 0x72, 0xee, 0x10, 0xdd, 0x01, 0x50,
		0x2d, 0x7a, 0xe1, 0xa9, 0x39, 0x39, 0xde, 0x20, 0x0d, 0x21, 0x20, 0xbd, 0x49, 0x6c, 0x60, 0xb3,
		0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x65, 0xce, 0x7d, 0xff, 0x00, 0x00, 0x00,
	},
	// uber/cadence/sharddistributor/v1/executor.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xda, 0x4a,
		0x10, 0x3e, 0x06, 0x12, 0x85, 0x41, 0xe1, 0x98, 0x55, 0x7e, 0x38, 0x24, 0xd1, 0x41, 0xa8, 0x6a,
		0x23, 0xa4, 0xd8, 0x85, 0xdc, 0x54, 0xcd, 0x4d, 0x9d, 0xd8, 0x02, 0x47, 0x60, 0x47, 0xb6, 0xa1,
		0xbf, 0x91, 0xb5, 0xe0, 0x2d, 0x41, 0x89, 0x6d, 0x6a, 0x2f, 0xa4, 0xa9, 0x7a, 0xd9, 0x37, 0xe8,
		0x8b, 0xf4, 0x41, 0xfa, 0x06, 0x7d, 0x99, 0x0a, 0x1b, 0x82, 0x31, 0x54, 0x34, 0xb9, 0xb3, 0x67,
		0xe6, 0xfb, 0xbe, 0xf1, 0x7c, 0xb3, 0x5e, 0xe0, 0x87, 0x1d, 0xe2, 0xf1, 0x5d, 0x6c, 0x11, 0xa7,
		0x4b, 0x78, 0xff, 0x0a, 0x7b, 0x96, 0xd5, 0xf7, 0xa9, 0xd7, 0xef, 0x0c, 0xa9, 0xeb, 0xf1, 0xa3,
		0x0a, 0x4f, 0x3e, 0x93, 0xee, 0xf8, 0x99, 0x1b, 0x78, 0x2e, 0x75, 0x51, 0x71, 0x0c, 0xe0, 0x26,
		0x00, 0x2e, 0x0e, 0xe0, 0x46, 0x95, 0xd2, 0x8f, 0x14, 0xb0, 0x75, 0x82, 0x3d, 0xda, 0x21, 0x98,
		0x6a, 0xe4, 0xd3, 0x90, 0xf8, 0x14, 0xed, 0x43, 0xda, 0xc1, 0x36, 0xf1, 0x07, 0xb8, 0x4b, 0xf2,
		0x4c, 0x91, 0x39, 0x4c, 0x6b, 0xb3, 0x00, 0xfa, 0x1f, 0x32, 0x53, 0x19, 0xb3, 0x6f, 0xe5, 0x13,
		0x41, 0x1e, 0xa6, 0x21, 0xd9, 0x42, 0x75, 0x58, 0xf7, 0x29, 0xa6, 0x43, 0x3f, 0x9f, 0x2c, 0x32,
		0x87, 0xd9, 0xea, 0x73, 0x6e, 0x55, 0x1b, 0x9c, 0x34, 0x41, 0xeb, 0x01, 0x4e, 0x9b, 0xe0, 0xd1,
		0x57, 0xd8, 0x0a, 0xaa, 0xcd, 0xf0, 0xdd, 0xf4, 0xc8, 0xc0, 0xf5, 0xa8, 0x9f, 0x4f, 0x15, 0x93,
		0x87, 0x99, 0xea, 0xf9, 0x6a, 0xde, 0xf8, 0xa7, 0x71, 0xfa, 0xb8, 0x68, 0xa2, 0x12, 0x92, 0x49,
		0x0e, 0xf5, 0xee, 0x34, 0xe4, 0x2f, 0x24, 0xd0, 0x07, 0xd8, 0xb0, 0x09, 0xc5, 0x16, 0xa6, 0x38,
		0xbf, 0x16, 0x28, 0xbe, 0x7a, 0x84, 0x62, 0x73, 0x42, 0x11, 0xea, 0xdc, 0x33, 0x16, 0xbe, 0xc0,
		0xee, 0x1f, 0x9a, 0x41, 0x2c, 0x24, 0xaf, 0xc9, 0xdd, 0x64, 0xf2, 0xe3, 0x47, 0x24, 0xc3, 0xda,
		0x08, 0xdf, 0x0c, 0x49, 0x30, 0xed, 0x4c, 0xf5, 0x78, 0x75, 0x1f, 0x0b, 0xdc, 0x5a, 0xc8, 0xf0,
		0x32, 0xf1, 0x82, 0x29, 0x9c, 0xc0, 0xe6, 0x5c, 0x5b, 0x4b, 0x14, 0xb7, 0xa2, 0x8a, 0xe9, 0x08,
		0xb8, 0x74, 0x07, 0xb9, 0x05, 0x72, 0x24, 0xdd, 0x7b, 0xce, 0x04, 0x9e, 0x1f, 0x3d, 0xac, 0xc3,
		0xa9, 0xe1, 0x07, 0x00, 0xa1, 0xe1, 0x37, 0x2e, 0x0e, 0x57, 0x8b, 0xd1, 0xd2, 0x41, 0xa4, 0xe1,
		0x62, 0xab, 0xf4, 0x2b, 0x01, 0xb9, 0xc8, 0x80, 0xfd, 0x81, 0xeb, 0xf8, 0x04, 0x8d, 0x20, 0x17,
		0x82, 0xb0, 0xef, 0xf7, 0x7b, 0x8e, 0x4d, 0x1c, 0x3a, 0x6e, 0x63, 0x6c, 0x98, 0xfc, 0x20, 0xc3,
		0x42, 0xbe, 0xb0, 0x31, 0x61, 0xc6, 0x15, 0x3a, 0xc7, 0xfa, 0xb1, 0x30, 0x6a, 0x43, 0xd6, 0xee,
		0xf7, 0x3c, 0x4c, 0xfb, 0xae, 0x63, 0xda, 0xae, 0x15, 0xce, 0x2a, 0x5b, 0xe5, 0x57, 0x8b, 0x36,
		0xa7, 0xb8, 0xa6, 0x6b, 0x11, 0x6d, 0xd3, 0x8e, 0xbe, 0x16, 0x46, 0xb0, 0xbd, 0xb4, 0x85, 0x25,
		0x2e, 0xd5, 0xe6, 0xf7, 0xa2, 0xf2, 0x97, 0x53, 0x9f, 0x31, 0x47, 0x8d, 0xbd, 0x84, 0x7f, 0x63,
		0x59, 0x74, 0x1e, 0xb3, 0xb5, 0xba, 0x5a, 0x60, 0x86, 0x9e, 0xf7, 0xb6, 0xfc, 0x8d, 0x81, 0xec,
		0xfc, 0x39, 0x47, 0x7b, 0xb0, 0x2b, 0xbd, 0x91, 0xce, 0x5a, 0x86, 0xaa, 0x99, 0xba, 0x21, 0x18,
		0x2d, 0xdd, 0x94, 0x95, 0xb6, 0xd0, 0x90, 0x45, 0xf6, 0x1f, 0x54, 0x80, 0x9d, 0x78, 0x52, 0x38,
		0x33, 0xe4, 0xb6, 0xc4, 0x32, 0x68, 0x1f, 0xf2, 0xf1, 0x9c, 0xa8, 0x09, 0xb2, 0x22, 0x2b, 0x35,
		0x36, 0xb1, 0x8c, 0x36, 0xc8, 0x4a, 0x22, 0x9b, 0x2c, 0xb7, 0x21, 0x13, 0xd9, 0x3c, 0x94, 0x87,
		0x2d, 0xbd, 0x2e, 0x68, 0xe2, 0xa2, 0xfe, 0x0e, 0xa0, 0xb9, 0x8c, 0x26, 0x09, 0xe2, 0x5b, 0x96,
		0x41, 0xdb, 0x90, 0x9b, 0x8b, 0x8b, 0xaa, 0x22, 0xb1, 0x89, 0xb2, 0x02, 0x6c, 0xfc, 0xd3, 0xd1,
		0x01, 0xfc, 0x27, 0xe8, 0xba, 0x5c, 0x53, 0x9a, 0x92, 0x62, 0x2c, 0x2a, 0xec, 0xc1, 0xee, 0x62,
		0x7a, 0x22, 0x53, 0xfe, 0xc9, 0xc0, 0xe6, 0xdc, 0x9a, 0x8c, 0x07, 0xd2, 0x94, 0x6b, 0x9a, 0x60,
		0xc8, 0xaa, 0x62, 0x36, 0x55, 0x51, 0x8a, 0x50, 0x3d, 0x81, 0x62, 0x2c, 0xd7, 0x50, 0xcf, 0x84,
		0x86, 0x79, 0x21, 0xe8, 0xba, 0x51, 0xd7, 0xd4, 0x56, 0xad, 0x1e, 0x8e, 0x2d, 0x56, 0xa5, 0x2a,
		0xa7, 0xaa, 0xa0, 0x89, 0x92, 0xc8, 0xa6, 0x4a, 0xa9, 0x8d, 0x04, 0x9b, 0x28, 0xa5, 0x36, 0x92,
		0x6c, 0xb2, 0xfc, 0x6c, 0x15, 0x9b, 0xa9, 0xd7, 0x05, 0x51, 0x7d, 0x5d, 0x7e, 0x1a, 0x2b, 0x14,
		0x65, 0xdd, 0xd0, 0xe4, 0xd3, 0x96, 0x21, 0x89, 0xd1, 0xf2, 0xea, 0x77, 0x06, 0xf6, 0x82, 0xb9,
		0x8b, 0xb3, 0x75, 0x99, 0x6e, 0x83, 0x70, 0x21, 0x23, 0x0a, 0xe9, 0xfb, 0x93, 0x88, 0xaa, 0x0f,
		0xff, 0xcf, 0x16, 0x8e, 0x1f, 0x71, 0xd4, 0x4f, 0x2f, 0xdf, 0xbd, 0xef, 0xf5, 0xe9, 0xd5, 0xb0,
		0xc3, 0x75, 0x5d, 0x7b, 0x7a, 0xb3, 0x1e, 0xdd, 0xba, 0xde, 0xf5, 0xc7, 0x1b, 0xf7, 0x36, 0xbc,
		0x62, 0x8f, 0x6c, 0xec, 0xe0, 0x1e, 0xf1, 0x78, 0xae, 0x47, 0x1c, 0x3e, 0xb8, 0x58, 0x97, 0xdd,
		0xbd, 0x27, 0xf1, 0xd8, 0xa8, 0xd2, 0x59, 0x0f, 0xaa, 0x8f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
		0xf5, 0x11, 0x14, 0xb3, 0xb9, 0x07, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorAPIYARPCClient {
			return NewShardDistributorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
